#!/bin/bash

declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"

function main() {
	while getopts "h" opt; do
		case $opt in
			h) printf "\e[1;34mUSAGE:\e[0m %s INPUT_FILE\n" "$(basename "$0")" && exit 0 ;;
			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
		esac
	done

	shift $((OPTIND - 1))

	local file="$1"

	[[ -z "$file" ]] && printf "%b No input file provided. Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1
	[[ ! -f "$file" ]] && printf "%b File '%s' does not exist.\n" "$FORMAT_ERROR" "$file" >&2 && exit 1

	case $file in
		*.mp4|*.mkv|*.mp3|*.avi|*.flac|*.wav|*.oog|*.m4a)  mpv "$file" ;;
		*.png|*.webp|*.jpeg|*.jpg|*.svg|*.gif|*.bmp)       nsxiv "$file" ;;
		*.pdf|*.epub)                                      zathura "$file" ;;
		*.csv)                                             sheets "$file" ;;
		*.pptx|*.ppt|*.odp)                                libreoffice --impress "$file" ;;
		*.docx|*.doc|*.odt)                                libreoffice --writer  "$file" ;;
		*.torrent)                                         fragments "$file" ;;
		*) printf "%b $file cannot be open via open() %b.\n" "$FORMAT_ERROR" >&2 && exit 1 ;;
	esac

	return 0
}

main "$@"
